name: Sanity tests

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        poetry-version: ["1.4.2"]
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.3.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Set up Poetry virtual environment
        run: poetry env use python${{ matrix.python-version }}
      - name: Install project dependencies
        run: poetry install
      - name: Run black
        run: poetry run black --check shamir tests
      - name: Run flake8
        run: poetry run flake8 --count shamir tests
      - name: Run tests with Poetry
        run: |
          poetry run pytest --junit-xml=junit/test-results-${{ matrix.python-version }}.xml --cov=shamir --cov-branch --cov-report=xml -n auto
      - name: Upload pytest test results
        uses: actions/upload-artifact@v3.1.2
        with:
          name: test-results-${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.python-version }}.xml
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
