name: Coverage report
on:
  push:
    branches:
      - "develop"
permissions:
  contents: read
jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
        poetry-version: ["1.7.1"]
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@a5643c67b5fcc9ac5eddb395c7f61b1b66d86034 # v2.4.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Set up Poetry virtual environment
        run: poetry env use python${{ matrix.python-version }}
      - name: Install project dependencies
        run: poetry install
      - name: Run tests with Poetry
        run: |
          poetry run pytest --junit-xml=junit/test-results-${{ matrix.python-version }}.xml --cov=shamir --cov-branch --cov-report=xml -n auto
      - name: Code Coverage
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
        with:
          files: coverage.xml
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }}
