name: CodSpeed Benchmarks

on:
    push:
        branches:
            - "develop"
    pull_request:
    workflow_dispatch:

jobs:
    benchmarks:
        name: Run benchmarks
        runs-on: ubuntu-latest
        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
              with:
                egress-policy: audit

            - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
            - name: Install uv
              uses: astral-sh/setup-uv@61cb8a9741eeb8a550a1b8544337180c0fc8476b # v7.2.0

            - name: Set up Python
              uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
              with:
                  python-version: "3.13"

            - name: Install dependencies
              run: uv sync --all-extras --dev
            - name: Run the benchmarks
              uses: CodSpeedHQ/action@94b88560ad3ed11ed5e92a321518a47c35a1fed5 # v4.8.0
              with:
                  mode: simulation
                  run: uv run pytest --codspeed -m benchmark
                  token: ${{ secrets.CODSPEED_TOKEN }}
